#aula numero 1
print('Aló Mundo!')
nun = int(input	(' Estou pedindo um número inteiro, informe: '))
#print (type(nun))
print('O número informado foi ', nun)
bime1 = float(input(' Qual foi sua nota no 1º Bimestre: '))
bime2 = float(input(' Qual foi sua nota no 2º Bimestre: '))
bime3 = float(input(' Qual foi sua nota no 3º Bimestre: '))
bime4 = float(input(' Qual foi sua nota no 4º Bimestre: '))
print ('A sua média foi: ', (bime1 + bime2 + bime3 + bime4) / 4)
raio = float(input(' Qual o raio do círculo que vc quer calcular a área: '))
print ('A área é: ', ( 3.1415 * raio ** 2), 'm2')
temper = float(input(' Qual a temperatura em Fahrenheit: '))
print ('A temperatura ', temper, '°F é ', (5 * ( temper - 32)/9 ), '°C')
